#!/bin/bash
echo Start testing

echo list of main folder before touch
ls
touch test.txt

echo list of main folder after touch
ls

echo list of main static folder before touch
ls
touch ~/target/classes/static/test.txt

echo list of main static folder after touch
ls
